# Generated by Django 5.0.2 on 2024-02-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("calories", models.DecimalField(decimal_places=2, max_digits=200)),
                ("cabohydrate", models.DecimalField(decimal_places=2, max_digits=200)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=200)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=200)),
                (
                    "measurement_scale",
                    models.CharField(choices=[("grams", "grams")], max_length=50),
                ),
                ("serving_size", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
