name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Create constraint file for Cython 3.0.0
      run: |
        echo "Cython<3" > cython_constraint.txt
        PIP_CONSTRAINT=cython_constraint.txt pip install "ai-core-sdk[aicore-content]"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django Testing
      run: |
        python manage.py test
        